/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.ac.exeter.opendayrace;

import uk.ac.exeter.opendayrace.ui.Renderer;

public class OpenDayRace {
    public static void main(String[] args) {
        new Renderer();
    }
}
