/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.ac.exeter.opendayrace;

import uk.ac.exeter.opendayrace.ui.Renderer;

public class OpenDayRace {
    public static void main(String[] args) {
        // Enable hardware acceleration
        System.setProperty("sun.java2d.opengl", "true");
        Renderer r = new Renderer();
        while (true) {
            r.run();
        }
    }
}
